# Generated by Django 3.2.9 on 2022-01-03 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ans',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
