# Generated by Django 3.2.9 on 2022-01-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_alter_question_ans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
