# Generated by Django 3.2.9 on 2022-01-04 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_alter_quiz_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taskperformance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('instruction', models.CharField(max_length=200)),
                ('max_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TakenQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken_quizzes', to='student_management_app.quiz')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken_quizzes', to='student_management_app.students')),
            ],
        ),
        migrations.CreateModel(
            name='SubmitedTaskperformance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('work_file', models.FileField(upload_to='')),
                ('score_result', models.IntegerField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submited_task', to='student_management_app.students')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submited_task', to='student_management_app.taskperformance')),
            ],
        ),
    ]
