# Generated by Django 3.2.9 on 2022-01-04 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_alter_takenquiz_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskperformance',
            name='module_id',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.modules'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskperformance',
            name='section_id',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.section'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskperformance',
            name='staff_id',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.staffs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskperformance',
            name='subject_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.subjects'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submitedtaskperformance',
            name='score_result',
            field=models.IntegerField(blank=True),
        ),
    ]
