# Generated by Django 3.2.9 on 2022-01-05 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0007_auto_20220104_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitedtaskperformance',
            name='score_result',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_grading', models.IntegerField(blank=True)),
                ('second_grading', models.IntegerField(blank=True)),
                ('third_grading', models.IntegerField(blank=True)),
                ('fourth_grading', models.IntegerField(blank=True)),
                ('final_grading', models.IntegerField(blank=True)),
                ('school_year_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.schoolyearmodel')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.students')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_year_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.schoolyearmodel')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_management_app.section')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student_management_app.subjects')),
            ],
        ),
    ]
