# Generated by Django 3.2.9 on 2022-01-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0009_auto_20220105_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradelevelmodel',
            name='grade_level_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='grades',
            name='final_grading',
            field=models.IntegerField(blank=True, default=90),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grades',
            name='first_grading',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grades',
            name='fourth_grading',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grades',
            name='second_grading',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grades',
            name='third_grading',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
