# Generated by Django 3.2.9 on 2022-01-11 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0010_auto_20220105_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='final_grading',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='grades',
            name='first_grading',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='grades',
            name='fourth_grading',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='grades',
            name='second_grading',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='grades',
            name='third_grading',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
