# Generated by Django 3.2.9 on 2022-01-11 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0011_auto_20220111_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stud_grades', to='student_management_app.students'),
        ),
    ]
