# Generated by Django 3.2.9 on 2022-01-11 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0012_alter_grades_student_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grades',
            unique_together={('student_id', 'subject_id')},
        ),
    ]
