# Generated by Django 3.2.9 on 2022-01-12 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0013_alter_grades_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='updated_at',
        ),
    ]
