# Generated by Django 3.2.9 on 2022-01-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0020_alter_students_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradelevelmodel',
            name='grade_level_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='gradelevelmodel',
            unique_together={('sy_id', 'grade_level_name')},
        ),
    ]
